using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DAL.Interfaces.Users;
using Domain;
using Domain.People;

namespace DAL.Interfaces
{
    public interface IUOW
    {
        //save pending changes to the data store
        void Commit();
        void RefreshAllEntities();

        //get repository for type
        T GetRepository<T>() where T : class;

        //Standard repos, autogenerated
        IEFRepository<ContactType> ContactTypes { get; }

        //Customs repos, manually implemented
        IPersonRepository People { get; }
        IContactRepository Contacts { get; }

        IUserRepository Users { get; }
        IUserRoleRepository UserRoles { get; }
        IRoleRepository Roles { get; }
        IUserClaimRepository UserClaims { get; }
        IUserLoginRepository UserLogins { get; }
    }
}